# Config for analysis

# ----------------------------------------------------------------------------
# Details on repo used for docs
# ----------------------------------------------------------------------------
github_repo: flu_h3_hk19_dms
github_user: jbloomlab
github_branch: main
description: Deep mutational scanning of A/HongKong/45/2019
year: 2022
authors: Frances Welsh, Timothy Yu, and Jesse Bloom

# ----------------------------------------------------------------------------
# Input data
# ----------------------------------------------------------------------------
pacbio_runs: data/pacbio_runs.csv  # PacBio sequencing data
barcode_runs_wo_sample: data/barcode_runs.csv  # barcode sequencing w/o sample annotation

# amplicons to which we align PacBio
amplicons:  # files containing the amplicons
  plasmid: data/hk19_pacbio_amplicon.gb
amplicon_specs:  # alignparse parsing speces for amplicons
  plasmid: data/feature_parse_specs.yaml
amplicons_of_interest:  # names of amplicons for which we keep/analyze CCSs
  plasmid: hk19_amplicon
gene: ha  # name of gene in amplicons

# designed mutations in the library
designed_mutations: library_design/aggregated_mutations.csv
designed_mutation_types:  # types of designed mutations in order handled
  - paired_epitope_mutation
  - epitope_mutation
  - viable_mutation

# barcodes for the neutralization standards
neut_standard_barcodes: data/neutralization_standard_barcodes.csv

# Parameters for processing Illumina barcodes
illumina_barcode_parser_params:
  upstream: GGCAACATCCGATGCAACATCTGTATATAATGAG
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0
  bc_orientation: R2

# only keep samples with an average of at least many counts per variant
min_avg_counts: 20

# Parameters for escape-probability calculation
prob_escape_min_neut_standard_count: 1000
prob_escape_min_neut_standard_frac: 0.0001
prob_escape_min_no_antibody_counts: 20
prob_escape_min_no_antibody_frac: 0.000001

# ----------------------------------------------------------------------------
# Parameters for analysis
# ----------------------------------------------------------------------------
# Parameters for building PacBio CCS consensuses
max_ccs_error_rate: 1.0e-4  # only keep CCS if gene/barcode error rate <= this
consensus_params:  # parameters for building PacBio consensus sequences
  max_sub_diffs: null
  max_indel_diffs: null
  max_minor_sub_frac: 0.2
  max_minor_indel_frac: 0.2
  min_support: 1 # edit for current limited sequencing data

# ----------------------------------------------------------------------------
# Names of output directories / files
# ----------------------------------------------------------------------------
# gene sequence and site numbering
gene_sequence_codon: results/gene_sequence/codon.fasta
gene_sequence_protein: results/gene_sequence/prot.fasta
site_numbering_map: data/site_map.csv

# processing of PacBio CCSs to create codon-variant table
process_ccs_dir: results/process_ccs
aligned_ccs_files:
  plasmid: results/process_ccs/CCSs_aligned_to_plasmid_amplicon.csv
nt_variants:
  plasmid: results/variants/plasmid_nt_variants.csv
codon_variants:
  plasmid: results/variants/plasmid_codon_variants.csv
virus_variants_w_neut_standard: results/variants/virus_variants_w_neut_standard.csv

# barcode sequencing
barcode_runs: results/barcode_runs/barcode_runs.csv  # with sample names added
barcode_counts_dir: results/barcode_runs/counts_by_sample
barcode_counts_invalid_dir: results/barcode_runs/counts_invalid_by_sample
barcode_fates_dir: results/barcode_runs/fates_by_sample
barcode_counts: results/barcode_runs/barcode_counts.csv

# codon-variant table and computed scores
codon_variant_table_pickle: results/variants/codon_variant_table.pickle

# computed escape probabilities for antibody selections
antibody_selections: results/prob_escape/selections.csv
variant_prob_escapes: results/prob_escape/prob_escapes.csv
